apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
