apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/deployment.yaml
- backend/service.yaml
- backend/pdb.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- frontend/pdb.yaml

images:
- name: 654654554686.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newName: 654654554686.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/backend
  newTag: sha-8ee10e2
- name: 654654554686.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newName: 654654554686.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop/production/frontend
  newTag: sha-8ee10e2

commonLabels:
  app.kubernetes.io/part-of: dvn-workshop
  environment: production
